config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#info'
  get 'pages/info'
  resources :subscriptions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subscription.rb
class Subscription < ApplicationRecord
	belongs_to :user
	enum frequency: { Yearly: 0, Quarterly: 1, Monthly: 2, Weekly: 3, Daily: 4 }
	enum subtype: { Fixed: 0, Variable: 1 }
	enum status: { Pending: 0, Scheduled: 1, Paid: 2 }
	enum autopay: { No: 0, Yes: 1 }
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to subscriptions_url, :alert => exception.message }
    end
  end

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    # @subscriptions automatically set to Subscription.accessible_by(current_user) by CanCan
    @subscriptions = @subscriptions.order(due_date: :asc)
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
    # @subscription automatically set to Subscription.find(params[:id])
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
    # @subscription automatically set to Subscription.find(params[:id])
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = current_user.subscriptions.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:title, :details, :type, :frequency, :autopay, :statement_date, :due_date, :amount, )
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription, local: true) do |form| %>

  
  <!-- Error Display -->
  <% if subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <!-- Subscription Form -->
  <div class="field" id="title">
    <%= form.label :title, "Who is this bill paid to?" %>
    <%= form.text_field :title %>
  </div>

  <div class="field" id="details">
    <%= form.label :details, "Any additional details for this bill?" %>
    <%= form.text_field :details %>
  </div>

  <div class="field" id="subtype">
    <%= form.label :subtype, "Is the amount the same each month or variable?" %>
    <span id="fixed-amount">
      <%= form.radio_button :subtype, 'Fixed' %>
      <%= form.label :subtype_fixed, 'Fixed Amount', :value => 'Fixed', :style => "display: inline-block;" %>
    </span>
    <br>
    <span id="variable-amount">
      <%= form.radio_button :subtype, 'Variable' %>
      <%= form.label :subtype_variable, 'Variable Amount', :value => 'Variable', :style => "display: inline-block;" %>
    </span>
  </div>

  <div class="field" id="frequency">
    <%= form.label :frequency, "How often does this bill come?" %>
    <%= form.select :frequency, Subscription.frequencies.keys.to_a %>
  </div>

  <div class="field" id="autopay">
    <%= form.label :autopay, "Is it setup to autopay?" %>
    <%= form.select :autopay, Subscription.autopays.keys.to_a %>
  </div>

  <div class="field" id="statement-date">
    <%= form.label :statement_date, "When will the next statement for this bill come?" %>
    <%= form.date_select :statement_date %>
  </div>

  <div class="field" id="due-date">
    <%= form.label :due_date, "When is the next time this bill due?" %>
    <%= form.date_select :due_date %>
  </div>

  <div class="field" id="amount">
    <%= form.label :amount, "What amount is the bill for?" %>
    <%= form.text_field :amount %>
  </div>


  <!-- Submit or Cancel Form -->
  <div class="actions">
    <%= form.submit %>
    <%= link_to :back do %><button value="Cancel">Cancel</button><% end %>
  </div>


<% end %>

app/views/subscriptions/edit.html.erb
<div class="section">
	<h1>Edit <%= @subscription.title %></h1>
</div>
<br>

<%= render 'form', subscription: @subscription %>

app/views/subscriptions/index.html.erb
<div class="container-fluid">
  <div class="row section">
    <div class="col-md-12">
      <h1>Bills & Subscriptions</h1>
    </div>
  </div>
  <br>

  <div class="section" id="subscription-list">
    <% @subscriptions.in_groups_of(4) do |group| %>
      <div class="row">
        <% group.compact.each do |subscription| %>
          <div class="col-md-3 list-links">
            <%= link_to subscription do %>
              <div class="subscription">
                <h4><%= subscription.title %></h4>
                <p><%= subscription.details %><br>
                  <%= number_to_currency subscription.amount %><br>
                  <%= subscription.due_date %><br>
                  <%= subscription.status %></p>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
      <br>
    <% end %>
  </div>
  <br>

  <div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-4 list-links">
      <%= link_to new_subscription_path do %>
        <div class="new-subscription">
          <h4>Create a New Subscription</h4>
        </div>
      <% end %>
    </div>
  </div>
  
</div>

app/views/subscriptions/new.html.erb
<div class="section">
	<h1>New Subscription</h1>
</div>
<br>

<%= render 'form', subscription: @subscription %>

app/views/subscriptions/show.html.erb
<container class="container">
	<div class="row">
		<div class="col-md-3 subscription">
			<h4><%= @subscription.title %></h4>
			<p><b>Amount: </b><%= number_to_currency @subscription.amount %></p>
			<p><b>Due Date: </b><%= @subscription.due_date %></p>
			<p>
				<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
				<%= link_to 'Delete', @subscription, data: { confirm: 'Are you sure?' }, method: :delete %>
			</p>
		</div>
	</div>
	<br>
	<div class="row">
		<p><%= link_to 'Return to List', subscriptions_path %></p>
	</div>
</container>